[package]
name = "cardinal-c"
version = "0.1.0"
authors = ["Zack <trimorphyt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cardinal-codegen = { path = "../codegen", version = "0.1.0" }